development:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: monologue_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: monologue_test
  pool: 5
